# docker build -t internationalbrainlab/alyx:apache -f Dockerfile.apache .
version: "2"

services:
  django-apache2:
    build: .
    container_name: django-deployment
    ports:
      - '80'
      - '443'
    volumes:
      - $PWD/../../..:/var/www/alyx
