name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  run_jobs:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Generate pip freeze requirements_frozen.txt
        run: |
          date > date_generated.txt
      - name: Setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Commit requirements_frozen.txt to repo
        run: |
          echo '>>> git status <<<'
          git status
          git add date_generated.txt
          git commit -m "GitHub Actions generated requirements_frozen.txt"
          git push
